
spring:
  cache:
    type: redis
    cache-names: redis-cache
  data:
    redis:
      host: localhost
      port: 6379
      password: dm5kZ3VvZXJ0cmdkdmNueWRna3M=
  datasource:
    url: jdbc:postgresql://localhost:5432/tasklist?currentSchema=tasklist
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: never
      continue-on-error: false
#      data-locations: classpath:demo_data.sql
  liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: true
    default-schema: tasklist

mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
security:
  jwt:
    secret: bHNrZGZhODRpM3RrLi5mZ21hZ25hLms0LmszbmtuNGsubG1sc21iZHBmcDkzNHRsMzRqYjt6cmR0aTNnYWVnczVnZzQ1NA==
    access: 3600000
    refresh: 2592000000
springdoc:
  override-with-generic-response: false
