
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tasklist?currentSchema=tasklist
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      continue-on-error: false
#      data-locations: classpath:demo_data.sql
security:
  jwt:
    secret: bHNrZGZhODRpM3RrLi5mZ21hZ25hLms0LmszbmtuNGsubG1sc21iZHBmcDkzNHRsMzRqYjt6cmR0aTNnYWVnczVnZzQ1NA==
    access: 3600000
    refresh: 2592000000
